before_script:
  - sudo apt-get install pandoc
# here you can check os environment, it is ubuntu natty  
  - uname -a
  - lsb_release -a
  - pandoc -v 
  - sudo apt-get install ttf-arphic-gbsn00lp ttf-arphic-ukai ttf-wqy-microhei ttf-wqy-zenhei
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra
  - gem install mkbok

rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
script: which mkbok ; mkbok --lang zh --build pdf

after_script:
  - ls -al *.pdf
  - mkdir ~/.ssh
  - cp id_rsa_mkbok ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git clone ssh://mkbok@repo.or.cz/srv/git/mkbok.git
  - cd mkbok
  - cp ../sdcamp.pdf .
  - git add sdcamp.pdf
  - git config user.name "Larry Cai"
  - git config user.email "larry.caiyu@gmail.com"
  - git commit -am "add file"
  - git push origin master
