language: cpp
before_script:
#  - sudo apt-get install libglib2.0-dev
  - pwd
  #- git clone --recursive git://github.com/fletcher/peg-multimarkdown.git
  - git clone --recursive git://github.com/fletcher/MultiMarkdown-4.git
  #- cd peg-multimarkdown
  - cd MultiMarkdown-4
  - make
  - export PATH=$PATH:`pwd`
# here you can check os environment, it is ubuntu natty  
  - uname -a
  - lsb_release -a
  - sudo apt-get install ttf-arphic-gbsn00lp ttf-arphic-ukai ttf-wqy-microhei ttf-wqy-zenhei
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra

script:
  - pwd 
  - cd ..
  - ls contents/img
  - echo $PATH
  - which multimarkdown
  - ls -al
  - chmod +x mmd2bok
  - ./mmd2bok

env:
  global:
    - secure: "qkE5/TVKQV/+xBEW5M7ayWMMtFwhu44rQb9zh3n0LH4CkVb+b748lOuW3htc\nXfnXU8aGzOsQBeCJZQstfzsHFPkll+xfhk38cFqNQp7tpMo/AOZIkqd2AIUL\n0bgaFD+1kFAxKTu02m11xzkDNw6FuHMVvoMEQu/fo115i2YmWHo="  

after_script:
#  - ls -al *.pdf
  - env
#  - echo $GITHUB_TOKEN
#  - ls -al 
# change the name to indicate it is snapshot
# - git config --global github.upload-script-token $GITHUB_TOKEN
  - ./github-upload.rb sdcamp.zh.pdf larrycai/sdcamp --description "generated by travis-ci, $TRAVIS_JOB_ID" --force --name sdcamp.zh.snapshot.pdf --skip-ssl-verification -t $GITHUB_TOKEN
