before_script:
  - sudo apt-get install pandoc
# here you can check os environment, it is ubuntu natty  
  - uname -a
  - lsb_release -a
  - pandoc -v 
  - sudo apt-get install ttf-arphic-gbsn00lp ttf-arphic-ukai ttf-wqy-microhei ttf-wqy-zenhei
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra
  - gem install mkbok

rvm:
  - 1.9.3
script: which mkbok ; mkbok --lang zh --build pdf

after_script:
  - ls -al *.pdf
  - ls ~/.ssh
  - cp id_rsa_mkbok ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo "repo.or.cz,195.113.20.142 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAs7JJacVNc1wk/6RZqMHin5RwR/LdIcMGGeG6WG4Sl/wETY9KYUVd126Yb2MV7vBT/8dW0iE6u6+sRVM3Xn5MG9K2PvQ57SbIQ53FvR4qBCqYkSn5sKs2wt9GpXh2MFN5TuXth2d1BABSR2a1u461K8SKbhclPVeFCeligaI4lGc=" >> ~/.ssh/know_hosts
  - git clone ssh://mkbok@repo.or.cz/srv/git/mkbok.git mkbok.pdf
  - cd mkbok.pdf
  - cp ../sdcamp.zh.pdf .
  - git add sdcamp.zh.pdf
  - git config user.name "Larry Cai"
  - git config user.email "larry.caiyu@gmail.com"
  - git commit -am "add file"
  - git push origin master
