before_script:
  - sudo apt-get install pandoc
# here you can check os environment, it is ubuntu natty  
  - uname -a
  - lsb_release -a
  - pandoc -v 
  - sudo apt-get install ttf-arphic-gbsn00lp ttf-arphic-ukai ttf-wqy-microhei ttf-wqy-zenhei
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra

rvm:
  - 1.9.3
script: 
  - chmod +x mkbok
  - ./mkbok --lang zh --build pdf

env:
  global:
    - secure: "qkE5/TVKQV/+xBEW5M7ayWMMtFwhu44rQb9zh3n0LH4CkVb+b748lOuW3htc\nXfnXU8aGzOsQBeCJZQstfzsHFPkll+xfhk38cFqNQp7tpMo/AOZIkqd2AIUL\n0bgaFD+1kFAxKTu02m11xzkDNw6FuHMVvoMEQu/fo115i2YmWHo="  
    
after_script:
#  - ls -al *.pdf
  - env
#  - echo $GITHUB_TOKEN
#  - ls -al 
# change the name to indicate it is snapshot
  - cp sdcamp.zh.pdf sdcamp.zh.snapshot.pdf
# - git config --global github.upload-script-token $GITHUB_TOKEN
  - ./github-upload.rb sdcamp.zh.snapshot.pdf --skip-ssl-verification -t $GITHUB_TOKEN
